language: node_js
node_js:
  - stable
install: npm install
services:
  - mongodb
script: npm test
after_success: npm run coverage

deploy:
  provider: heroku
  api_key:
    secure: gdrZw0imygBEcxvaAxcSObj0zGM/iDaiBLeSWiwaS0bYu5cHTcA9eljMy7BPwlDss9pNj81Qc7QbZOS0fjPMrugTWSnkiitNq8NzpFNCgHbZC17kSkmLFR5l1uorecTXi1GBU+LWqO1MplLPwhcfTbyrXcXl444ORVYHCH0ZtQYjwiY0TqPEQTO8Yp+308ADP0BybvjnR3D98NR2HciFpg8skJQjSGcQX4AC3bglkjcTiu1RztQ5JzUeHUU1HIwNcHKO8BJ04N4XYjXUX86pMboFxswddmWMY9VSCbpFFF4f/C/T7GAynJXZpfpR69lK/Bi8IAFgasi4MBGytp3do93IJYjTZ+0aOYjqgy0vsrkd5r96yoLpfwg7O9P29eBvmGF7jjb6SkmlQET/NGLFUWsEw6pCaKnJ1OLZafndDY0WPvSgkLBDAnsq7kmOQSCJ7ToZLT4kE+Q/9EJEPZoGoMO4w/rJUPRd8iYV2xN52GLmDD5QPbjrPrDNv7MADfeiIkl0SFp9h0fDbhPGhvG742wD4MV+o4LwWMI74CJXU1AKe+2kXI0/02GJpggTcnqlzmI8wMtJ+OOIZIatUHjRLFqZd3BfeuKtuS5laUryyqvEBySvVorNErxkZ1BT9rrAYGrNiXPtZSkOpNVT60hbA3ENBzkZbRBdPrTGaw7lZJc=
  app: your-heroku-app-express
  on:
    repo: JordisGithub/mongodb-mongoose-express-ci
  run:
    - "node seed/userProjects.js"
